services:
  - type: web
    name: eve-corp-navigator-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_MONTHLY
        sync: false
      - key: STRIPE_PRICE_ID_WEEKLY
        sync: false
      - key: WHITELIST_GUILDS
        sync: false
      - key: BOT_PREFIX
        value: "!"
      - key: PORT
        value: "8000"
      - key: HOST
        value: "0.0.0.0"
